/**
 * Regenerates src/data/countries.generated.ts.
 *
 * Names come from i18n-iso-countries, dial codes from libphonenumber-js's full
 * metadata, and `hasFlag` from the SVGs actually present in flags/. Both source
 * packages are devDependencies: the generated file is checked in, so the
 * published package ships with no runtime dependencies.
 *
 * Run with `npm run generate` after bumping either source package.
 */
import { writeFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';
import { createRequire } from 'node:module';
import i18nCountries from 'i18n-iso-countries';

// require, not an import attribute: tsx and Node disagree about JSON import
// attributes for files reached through a package's exports map.
const require = createRequire(import.meta.url);
const metadata = require('libphonenumber-js/metadata.full.json');
const en = require('i18n-iso-countries/langs/en.json');

i18nCountries.registerLocale(en as Parameters<typeof i18nCountries.registerLocale>[0]);

const ROOT = join(import.meta.dirname, '..');

/**
 * ISO 3166 to ISO 4217. The first 50 entries are Khaime's own curated list,
 * lifted verbatim from @khaime/address in khaime-custom-sites; the rest extend
 * it to the shared-currency blocs (eurozone, XOF, XAF) and the African markets
 * Khaime already sells into. Countries absent here get `currency: undefined`
 * rather than a guess.
 */
const COUNTRY_CURRENCY: Record<string, string> = {
  // Curated in @khaime/address
  NG: 'NGN', GH: 'GHS', KE: 'KES', ZA: 'ZAR', EG: 'EGP', MA: 'MAD', TZ: 'TZS',
  UG: 'UGX', RW: 'RWF', ET: 'ETB', SN: 'XOF', CI: 'XOF', CM: 'XAF', GB: 'GBP',
  DE: 'EUR', FR: 'EUR', IT: 'EUR', ES: 'EUR', NL: 'EUR', BE: 'EUR', PT: 'EUR',
  IE: 'EUR', AT: 'EUR', CH: 'CHF', SE: 'SEK', NO: 'NOK', DK: 'DKK', FI: 'EUR',
  PL: 'PLN', US: 'USD', CA: 'CAD', MX: 'MXN', AE: 'AED', SA: 'SAR', IN: 'INR',
  SG: 'SGD', MY: 'MYR', PH: 'PHP', ID: 'IDR', TH: 'THB', JP: 'JPY', KR: 'KRW',
  CN: 'CNY', HK: 'HKD', AU: 'AUD', NZ: 'NZD', BR: 'BRL', AR: 'ARS', CO: 'COP',
  CL: 'CLP',
  // Remaining eurozone
  CY: 'EUR', EE: 'EUR', GR: 'EUR', HR: 'EUR', LT: 'EUR', LU: 'EUR', LV: 'EUR',
  MT: 'EUR', SI: 'EUR', SK: 'EUR',
  // West African CFA franc
  BJ: 'XOF', BF: 'XOF', GW: 'XOF', ML: 'XOF', NE: 'XOF', TG: 'XOF',
  // Central African CFA franc
  CF: 'XAF', CG: 'XAF', GA: 'XAF', GQ: 'XAF', TD: 'XAF',
  // Other African markets
  AO: 'AOA', BW: 'BWP', DZ: 'DZD', MW: 'MWK', MZ: 'MZN', NA: 'NAD', SD: 'SDG',
  TN: 'TND', ZM: 'ZMW',
  // Other frequently seen
  BD: 'BDT', CZ: 'CZK', HU: 'HUF', PE: 'PEN', PK: 'PKR', RO: 'RON',
  RU: 'RUB', TR: 'TRY', VN: 'VND',
};

/** Regional-indicator glyph for an alpha-2 code. No lookup table needed. */
function toEmoji(code: string): string {
  return String.fromCodePoint(
    ...[...code.toUpperCase()].map((c) => 0x1f1e6 + c.charCodeAt(0) - 65)
  );
}

const bundled = new Set(
  readdirSync(join(ROOT, 'flags'))
    .filter((f) => f.endsWith('.svg'))
    .map((f) => f.replace(/\.svg$/, '').toUpperCase())
);

const callingCodes = metadata.country_calling_codes as Record<string, string[]>;

type Row = {
  code: string;
  name: string;
  dialCode: string;
  currency?: string;
  isPrimaryForDialCode: boolean;
};
const rows: Row[] = [];

for (const [dial, codes] of Object.entries(callingCodes)) {
  codes.forEach((code, index) => {
    const name = i18nCountries.getName(code, 'en');
    if (!name) return; // non-country entries in the metadata
    rows.push({
      code,
      name,
      dialCode: `+${dial}`,
      currency: COUNTRY_CURRENCY[code],
      // libphonenumber lists the main country first for a shared calling code.
      // Sorting by name below throws that away, so capture it here.
      isPrimaryForDialCode: index === 0,
    });
  });
}

rows.sort((a, b) => a.name.localeCompare(b.name, 'en'));

const missingFlags = rows.filter((r) => !bundled.has(r.code)).map((r) => r.code);

const body = rows
  .map((r) => {
    const currency = r.currency ? ` currency: '${r.currency}',` : '';
    return `  { code: '${r.code}', name: ${JSON.stringify(r.name)}, dialCode: '${r.dialCode}',${currency} emoji: '${toEmoji(r.code)}', hasFlag: ${bundled.has(r.code)}, isPrimaryForDialCode: ${r.isPrimaryForDialCode} },`;
  })
  .join('\n');

const out = `// GENERATED by scripts/generate-countries.ts — do not edit by hand.
// Run \`npm run generate\` to refresh.
import type { Country } from '../types';

export const countries: readonly Country[] = Object.freeze([
${body}
]);
`;

writeFileSync(join(ROOT, 'src/data/countries.generated.ts'), out);

console.log(`countries: ${rows.length}`);
console.log(`bundled flag SVGs: ${bundled.size}`);
console.log(`with currency: ${rows.filter((r) => r.currency).length}`);
console.log(
  missingFlags.length
    ? `countries without a bundled flag (${missingFlags.length}): ${missingFlags.join(', ')}`
    : 'every country has a bundled flag'
);
